src/qudi/hardware/dummy/fast_counter_dummy.py
src/qudi/logic/pulsed/pulsed_measurement_logic.py

Fixes the x axis of exported pulsed thumbnails from html tags (`<sub>`). 
While the pulsed gui (based on pyqtgraph) supports html tags for the labels, the thumbnail export via matplotlib does not.
This fix transforms (only) html superscript `<sub>` tags to the required Latex format. Currently, `<sub>` is the only html tag used in predefined methods.
Dummy mode.
Buggy:
Fixed:

Fix pulsed labels

---

src/qudi/gui/pulsed/pulse_editors.py

The pulse editor gui was not showing digital channels correctly in its tabular view. The fix reverts changes made during the port; potentially by mistake.
Working again:

[Fix] Pulse editor gui 

---

src/qudi/hardware/fastcomtec/fastcomtecmcs6.py
src/qudi/logic/pulsed/sequence_generator_logic.py

1. Code cleanup in Fastcomtech code.
2. Maybe more controversial: It seems like some pulser do not strictly add a channel extension to their waveform and sometimes sequence names (eg. 'rabi_ch1'). Currently, this yields wrong results for loaded_assets. This fix is more foregiving, by first checking if the channel extension is used. Alternatively, one could make sure that all devices strictly follow the intended behavior.

Small fixes

---

src/qudi/hardware/spincore/pulse_blaster_esrpro.py

PulseBlaster was broken before due to not fulfilled SwitchInterface.
Fixed with dummy implemntations.
On real setup (M26/4219)

fix: not-fulfilled switch interface

---

src/qudi/gui/qdplot/qdplot_gui.py
src/qudi/gui/qdplot/qdplot_plot_dockwidget.py
src/qudi/logic/qdplot_logic.py

The QDPlotter now supports labels for the datasets.
A Label is shown in the GUI to distinguish multiple data sets in one plot. Same is also implemented for the saved data.
In the process, the way the clear attribute was handled has changed. Before the old data was "lost" in the logic, now it is saved.
Backwards compatible, as the labels are created automatically if not specified.
Tested on Win 10 Pro 21H2, python 3.8.10, qudi-core 1.0.1, qudi-iqo-modules 0.1.0, pyqtgraph 0.12.3

Label for qdplotter

---

src/qudi/hardware/awg/keysight_M3202A.py

Update the M3202 qudi AWG module to work with Keysight SD1 version 3.03.12 and AWG firmware version  04.02.45.
* Fix a longstanding syntax error
* Remove custom loading method working around slow loading in the SD1 Python module
* Set trigger behaviour to the old behaviour form SD1 2.x after Keysight support finally added the method
* Remove unused imports, rely on built-in dict ordering
This change is required to use the M3202A with the latest software from Keysight.
Tested in the test setup on my desk.

Keysight SD1 SFP 3.x fixes

---

docs/changelog.md
src/qudi/hardware/awg/keysight_M3202A.py

The keysight sometimes returns a null byte at the end of the string which crashes the manager GUI, so we strip it proactively.
Null bytes are a big NONO in python and should be avoided at all costs.
The origin of the null byte is the keysight hardware module, which we do not have access to, so we need to implement the fix null byte post call.
Avoid a crash of qudi by catching unwanted null bytes from the hardware.
Testes on Hardware with current qudi core in anaconda on python 3.8.12.

Fiy null bytes in Keysight module

---

docs/changelog.md
src/qudi/hardware/interfuse/ni_scanning_probe_interfuse.py
src/qudi/hardware/ni_x_series/ni_x_series_finite_sampling_io.py
src/qudi/interface/scanning_probe_interface.py

Rework of the data polling of the ni_scanning_interfuse.
The data poll now runs in a separate loop and the data poll is no longer triggered from the logic, as it should be. 
Before, a data poll was only executed upon request from the logic even though the hardware might have had more data ready. This has been fixed and the poll now requests a minimum number of "chunk_size" samples but also gathers more if they are already available.
Tested on Win10 21H2 and a PCIe-6323 Ni Card connected to Galvo Scanner for x,y and an open loop piezo for z.
Tested with various clock frequencies and scan resolutions in 1D and 2D scans.

Ni interfuse data polling

---

docs/changelog.md
src/qudi/hardware/fpga_pulser/ok_fpga_pulser.py

Fix broken QO Fpga Pulser
So far, the QO FPGA Pulser was relying on the core function get_appdata_dir, which restricted where to put the corresponding bitfiles. Now one can specify the directory where the bitfiles are residing via a mandatory config option, which also checks if the files exist.
It fixes the module which so far was not tested since porting.
Testetd on a Win10 21H2 office PC with an FPGA connected.

Qo fpga fixes

---

docs/changelog.md
setup.py
src/qudi/hardware/dummy/data_instream_dummy.py
src/qudi/hardware/ni_x_series/ni_x_series_in_streamer.py
src/qudi/interface/data_instream_interface.py
src/qudi/interface/pulser_interface.py
src/qudi/logic/time_series_reader_logic.py

Got rid of any import of deprecated module `qudi.core.interface`.
Only the pulsed and time series toolchain were impacted by this change.
`qudi.core.interface.ScalarConstraint` has been deprecated and was replaced by the quite different `qudi.util.constraints.ScalarConstraint`.
The new object has properties in place to provide the same interface as the old one.
Only on dummy. Testing is needed with real hardware for pulse generators (not critical due to minimal changes) and NI instreamer (critical due to interface change).

Refactor scalar constraint

---

src/qudi/gui/pulsed/pulsed_maingui.py
src/qudi/logic/pulsed/pulse_objects.py
src/qudi/logic/pulsed/sampling_functions.py
src/qudi/logic/pulsed/sequence_generator_logic.py

This continues [PR70](https://github.com/Ulm-IQO/qudi-iqo-modules/pull/70), which I had to close to clean up the messed up branch.
This PR introduces small changes to the pulsed toolchain that allow loaded predefined_methods more flexibility.
- Custom predefined methods may inherit from `PredefinedGeneratorPlugin`, additionally to the existing `PredefinedGeneratorBase`.
- This enable to:
1. Manipulate and even add their own `generation_parameters` (see screenshot)
2. Invoke code after the `PulseObjectGenerator` is initialized. This allows for numerous possibilies, eg. to influence the helper methods in pulse_objects.py (like  _get_mw_element() ) that are used from all predefined methods.
- I also added the possibily to have enum like `generation_parameters` correctly handled by the gui. …

Plugins to pulsed toolchain (clean)

---

docs/changelog.md
src/qudi/hardware/ni_x_series/ni_x_series_finite_sampling_input.py

Fix values retrieved from Ni Finite Sampling input to be "counts/second"
So far the Finite Sampling Input hardware module of the NI returns digital values which corresponded to "counts per clock cycle" and not "counts per second", as it is expected to be (and also as stated in the default config)
From the old qudi core, the unit of the values gotten from digital channels had typically been counts/second. So far the unit was and still is ignored completely. Maybe one should not even allow to configure this and always return the value in c/s? 
Tested on a simulated NI PCIe-6363 with up to date qudi-core.

Fix Counts per second in finite sampling input

---

src/qudi/logic/poi_manager_logic.py

One liner that fixes #87. This would crash with 
```
TypeError: cannot unpack non-iterable NoneType object
in save_roi()
x_extent, y_extent = self.roi_scan_image_extent
```
Tested on dummy.

Hotfix poimanagerlogic crash without image loaded 

---

src/qudi/hardware/awg/keysight_m819x.py

Keysight AWG allows a sample rate precision of 10mHz. So far the sample rate can only be set with 10MHz precision.
One line change to increase the number of digits where the sample rate is written to the AWG. 
The AWG allows for a higher resolution of sample rates than is used in Qudi so far. People might want (including at least me) to set the sample rate with higher precision. 
Tested with Keysight AWG M8195A on my setup. 
Might require testing with model 8190A (@timoML?). 

Increase Keysight AWG sample rate precision 

---

src/qudi/hardware/awg/tektronix_awg70k.py

Fixes a bug that prevented a correct pulsed asset name (and thus auto-invocation of pulsed settings) in sequence mode. 
The bug was introduced by [this commit](https://github.com/Ulm-IQO/qudi-iqo-modules/commit/8cc9f78c6ebff583be0943d0c6e5e1ee9e9aa42b), as it improved the postfix handling. However, now splitting the "_ch" postfix only when occuring at the end of the asset, this improvement broke due the additional postfix in sequence mode. This PR removes this additional sequence mode postfix.

[Hotfix] Tek 70k asset name

---

src/qudi/hardware/wavemeter/high_finesse_proxy.py

The HighFinesse wavemeter has exposed start/stop measurement functions. They start/stop the hardware-internal measurement loop. If this is not running, no new values are acquired.
This PR changes the qudi behavior to make sure to start the measurement but not to bother about stopping it once no qudi module is active anymore.
It also adds a check to properly catch an error code which indicates that the wavemeter app is not running and passes it to the user as an exception.
In this way, other processes that need wavemeter data are not affected. The most prominent example is the built-in laser stabilization of the wavemeter application as pointed out by @Nick-Grimm .
This was tested with a HighFinesse WS 7. Special testing with remote modules should not be necessary.
(syntax, indentation, …

wavemeter: don't stop measurement

---

src/qudi/hardware/microwave/mw_source_smbv.py
src/qudi/logic/odmr_logic.py

Quick bugfix of some typos in `mw_source_smbv`. 
Fixing four typing errors in the hardware file of mw generator Rohde&Schwarz SMB series as discovered and reported in [discussion #72](https://github.com/Ulm-IQO/qudi-core/discussions/72) in qudi-core. 
Additionally, add `default_scan_mode` ConfigOption in the example configuration in the docstring of the `odmr_logic`. This should show the user that the scan mode `JUMP_LIST` or `EQUIDISTANT_SWEEP` can be configured. 
Obvious typos are fixed. See also [discussion #72](https://github.com/Ulm-IQO/qudi-core/discussions/72) in qudi-core. 
Currently not tested with one of our hardware as it is not available. According to the author of the discussion, it should work. 

Bugfix typo in MW smbv

---

docs/changelog.md
src/qudi/hardware/microwave/mw_source_srssg.py

This PR introduces improvements to the microwave hardware file for Stanford Research Systems (SRS) signal generators.
- support for all current SRS signal generators (see [manufacturer website](https://www.thinksrs.com/products/test.html))
- proper matching of the model identifier to supported functions and hardware constraints
- check for error after every write command
- display current frequency during scan
- type annotations and documentation
We are using a non-vector SRS signal generator in our lab. It was not compatible with the current hardware file due to the usage of commands which are defined exclusively for vector models.
Tested on real hardware (SG384) with the ODMR toolchain.

improved support for SRS signal generators

---

docs/changelog.md
src/qudi/hardware/ni_x_series/ni_x_series_finite_sampling_input.py

add support for devices with voltage-high sensitive triggers
Adds option for a config flag invert_trigger_polarity, that if checked, changes the idle_state of the NI output channels to HIGH instead of LOW and changes the edge types to FALLING instead of RISING edges
Some devices, e.g. the microwave generators from the company Windfreak Technologies are LOW-sensitive, so trigger pulses have to consider that. A LOW idle state causes unwanted triggering. Also the edges have to be changed.
#105 
The fix has been tested by checking sweeps of the microwave signal with qudi's odmr module, using a Windfreak SynthNV Pro connected to an oscilloscope to check the output. With the fix, no unwanted triggering occurs anymore.

add support for devices with voltage-high sensitive triggers

---

src/qudi/hardware/awg/tektronix_awg70k.py

Docstring example config with small letter is not loadable

Fix docstring typo

---

src/qudi/gui/scanning/scan_widget.py

There is now another label in the Scan2DWidget showing you 
the position of the mouse cursor.
It is additional information allowing one to get the exact position of e.g. a colorcenter
without actually moving the scanner.
Only on dummy for now
We should probably check performance across different setups
and find a sensible default for the polling rate of the cursor position.

Introducing cursor position in Scan2DWidget

---

src/qudi/hardware/microwave/mw_source_windfreak_synthhdpro.py

Added documentation that the MW source is low active and needs a falling edge when using triggers. Using the `ni_x_series_finite_sampling_input` one can change the config option for the trigger edge. 
Users have run into this problem. First the option to change the trigger edge has beed added with PR #122. After that users still ran into the same problem because the necessity to change the trigger edge is not stated in the hardware file. 
Not tested, only change in the docstring. 

Windfreak synthHD documentation for falling trigger edges

---

docs/changelog.md
src/qudi/logic/odmr_logic.py

Remove old fits when starting a new ODMR measurement
As discussed in https://github.com/Ulm-IQO/qudi-iqo-modules/discussions/137, all fits are removed when starting a new ODMR measurement.
Old fits were not removed when starting a new measurement, which could be annoying especially when the frequency range changed between the old and the new measurement.
Tested with dummy configuration, which should not matter

Remove old odmr fits

---

src/qudi/hardware/ni_x_series/ni_x_series_in_streamer.py

If there are two NI cards connected and each has an analog input on the same pfi channel, then both counter GUIs cannot be run simultaneously because the task names are identical.
For experiments using multiple NI cards, it is possible that the same pfi channel is used and it causes the new task to have the same name as the old task. This crashes the time series gui.
Tested scanner and time series gui on my two-foci confocal setup and it worked fine. Have not tested any other modules since I don't use anything else.
Also the old core did not have this problem because there was a check to make sure task names were unique: https://github.com/Ulm-IQO/qudi/blob/ac37d66a1a89afaef455bf67699fcc189c1b60b2/hardware/ni_x_series_in_streamer.py#L874-L882
(syntax, indentation, mutable default values, …

Fixes issue with using same pfi channel on two different ni cards for NI instreamer

---

src/qudi/logic/poi_manager_logic.py

POI manager auto-find fix
When running the (cool) auto-find feature in the POI manager, the POIs did not match the bright spots but appeared to be rotated by 90°. The issue seemed to stem from an unnecessary transpose operation on the image data, which has now been removed. Additionally, if the POI diameter was smaller than the image step size, an exception was thrown due to a filter size of 0. This has been resolved by ensuring that the filter size is at least 1.
After these changes the feature seems to run as expected
Tested only with dummy configuration, which should not matter

POI manager auto-find fix

---

docs/changelog.md
src/qudi/logic/pulsed/predefined_generate_methods/basic_predefined_methods.py

The current rotating_frame=False will brake the phases of MW pulses in the experiment.

fix rotating frame in hahn_echo_exp

---

docs/changelog.md
src/qudi/hardware/fastcomtec/fastcomtecmcs6.py

Get the current number of sweeps and runtime of the FastComtec MCS6 while running a measurement. 
The FastComtec counter model MCS6 has the possibility to read the number of sweeps and runtime when a measurement is performed. This has not been implemented so far and is added with this PR. 
The info_dict when getting the data trace returns `None`. Also when the measurement is saved the information about the elapsed sweeps will not be saved. By simply querying the sweeps and runtime of the fastcounter the values are available for the user especially once the measurement is saved. 
Tested on my setup with real hardware MCS6A. 

Fastcomtec get sweeps

---

docs/changelog.md
src/qudi/logic/qdplot_logic.py

The plot in qdplot was not saved when fitting was used 
This was caused by improper handling of fit_results.
In qdplot_logic.py, _last_fit_results is defined under QDPlotFitContainer as a dictionary.
When _plot_figure of QDPlotLogic is called for saving, this fir_results is used to retrieve the result.high_res_best_fit. 
Since the instance of ModelResult from lmfit is stored in the values of that dictionary, values() should be used.
Firstly, data is set by set_data method. After fitting with a function on gui, save_data method was called.

bugfix on unsaved fit figure in QDPlotter

---

docs/changelog.md
src/qudi/gui/scanning/scan_widget.py
src/qudi/gui/scanning/scannergui.py
src/qudi/logic/scanning_data_logic.py

Added a UI element in the scanner GUI for the user to specify a custom save file name for saved scans. Note that this is only appended to the default nametag that is generated which contains the timestamp.
Some users do multiple confocal scans and it is difficult to keep track of the scans since they are only saved with timestamps in the file name.
Tested on Ubuntu 22.04.4LTS with dummy modules and on Windows 10 (custom config for experiments) and it works fine in both. Note that the UI changes made here were based on those in the ODMR GUI.

Scanner customnametag

---

docs/changelog.md
src/qudi/gui/qdplot/qdplot_gui.py
src/qudi/logic/qdplot_logic.py

- Fixed the example config for copy and paste to link to the correct module.
- Fixed missing `plot_index` when calling `QDPlotLogic._remove_plot` in `QDPlotLogic._set_plot_count`. I chose to remove the oldest (lowest index = 0) plot.
- Copy paste config was not correct before
- `QDPlotLogic._remove_plot` will raise an exception when `QDPlotLogic._set_plot_count` is called, making the function unusable
Tested it by loading the module and calling `QDPlotLogic.set_plot_count`

Qdplotter bugfix

---

src/qudi/gui/scanning/scannergui.py

fix a bug in the checker of the `optimizer_plot_dims` config option of the scanner gui: allow for only 2D optimization (no 1D optimization)
I noticed this bug while setting up confocal for a system with only X and Y control, and only manual/external Z control. Setting the config option to `[2, 2]` did not work.
tested on an NI card system, but should be possible to test with scanner dummy as well

fix checker for optimizer plot dimensions

---

docs/changelog.md
src/qudi/gui/qdplot/plot_widget.py
src/qudi/gui/qdplot/qdplot_gui.py

When adding a new plot, existing plots will no longer close their Fit widget, displaying the fit results, when in tabbed mode. The feature is respecting the display state of each plot before the new plot was added, if a user hid the result manually it will not be shown after the addition of the new plot.
Whenever a new plot is added, the `restore_view` function is called. This function will reset the state of showing fits on all plots to an initial `False` state. This can be annoying when adding new plots and comparing them with each other, if suddenly the fit results disappear.
Confocal setup and dummy modules.

Qdplot GUI fit fix

---

docs/changelog.md
src/qudi/gui/scanning/scannergui.py
src/qudi/logic/scanning_data_logic.py
src/qudi/logic/scanning_optimize_logic.py
src/qudi/logic/scanning_probe_logic.py

Fixes the initialization error occuring when configuring scanner with less than 3 axes as described in #170 .
A bug caused in `_set_default_scan_sequence` to always raise the `NotImplementedError` in `_allowed_sequences` if the default `_optimizer_sequence_dimensions` were used with scanners that have less than 3 axes configured.
Dummy session having only x and y axis configured.

Hotfix for issue in #170

---

docs/changelog.md
src/qudi/logic/pulsed/predefined_generate_methods/basic_predefined_methods.py

When testing for #180, I discovered that `generate_t1_sequencing` is missing the `waiting_element` most of our pulse sequences have after the `laser_element` and `delay_element`.
In my particular case this caused the laser pulse to reach over into the next sweep, if only one datapoint is acquired.
With the fix it works as expected.
Probably, this stems from a badly calibrated laser delay or laser safety, so could be fixed by changing these values as well. However, I thought with this fix one could bring this pulse sequence in line with the others, adding the `waiting_element`.
Same confocal setup #180 was tested with.

Adding missing waiting element to `t1_sequencing` predefined method

---

docs/repo_management/release_workflow.md

fix typos and add documentation on testing of `test.pypi.org` release
When testing the current `test.pypi.org` release, using the command provided on the release page does not work.
We added this info in the docs.

fix typos and add documentation on testing of `test.pypi.org`  release
